love.filesystem.setIdentity("love2dstreamtest")
require("core.Utils")
require("core.Library")
require("bin")
GLOBAL,sThread=require("multi.integration.loveManager").init()
require("core.AudioManager")
require("core.GuiManager")
require("parseManager")
gui.ff.Color=Color.Black
